apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xb6t3onhw-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xb6t3onhw-java-quarkus-gitops